name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # run workflow when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug token length
        run: |
         echo "Token chars: $(echo -n "${{ secrets.DOCKERHUB_TOKEN }}" | wc -c)"

      - name: Log in to Docker Hub
        run:  echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
   
      - name: Build Docker image
        run: |
          docker build -t maithililok/my-devops-app:latest .

      - name: Push Docker image
        run: |
          docker push maithililok/my-devops-app:latest.

      - name: Confirm login works
        run: |
           docker info | grep -i Username

      - name: Confirm login works
        run: |
         docker info | grep -i Username

